/**
 * emoji-data.js — Standard emoji name mappings (gemoji/Discord names)
 *
 * Maps :name: syntax to Unicode emoji characters.
 * Categories for the emoji picker panel.
 */

window.EMOJI_MAP = {
  "grinning": "😀", "grimacing": "😬", "grin": "😁", "joy": "😂", "rofl": "🤣",
  "sweat_smile": "😅", "laughing": "😆", "innocent": "😇", "smiling_imp": "😈",
  "sunglasses": "😎", "monkey_smile": "🙈", "monkey": "🙉", "monkey_see": "🙊",
  "heart_eyes": "😍", "kissing_heart": "😘", "kissing": "😗", "kissing_smiling_eyes": "😚",
  "kissing_closed_eyes": "😙", "stuck_out_tongue": "😜", "stuck_out_tongue_winking_eye": "😜",
  "stuck_out_tongue_closed_eyes": "😝", "wink": "😉", "wink2": "😚", "smile": "😊",
  "blue_screen": "😃", "confused": "😕", "confounded": "😖", "kissing_cat": "😺",
  "cat": "🐱", "smirk": "😒", "unamused": "😒", "anguished": "😧", "awkward": "😮",
  "astonished": "😲", "frowning": "😠", "frowning2": "☹️", "hushed": "😯",
  "flushed": "😳", "sleepy": "😪", "worried": "😟", "cry": "😢", "sob": "😭",
  "disappointed": "😞", "relieved": "😌", "satisfied": "😄", "sweat": "😓",
  "tired_face": "😫", "sobbing": "😿", "anguished_face": "😧", "dizzy_face": "😵",
  "astonished_face": "😲", "weary": "😩", "exploding_head": "🤯", "face_with_thermometer": "🤒",
  "face_with_head_bandage": "🤕", "nauseated_face": "🤢", "face_vomiting": "🤮",
  "sneezing_face": "🤧", "hot_face": "🥵", "cold_face": "🥶", "poop": "💩",
  "face_with_symbols": "🤬", "cowboy_hat_face": "🤠", "clown_face": "🤡",
  "lying_face": "🤥", "shushing_face": "🤫", "face_with_hand_over_mouth": "🤭",
  "drooling_face": "🤤", " Zoning": "🤐", "zipper_mouth": "🤐",
  "thermometer": "🌡", "sweat_drops": "💧", "droplet": "💧", "dash": "💨",
  "wave": "👋", "raised_back_of_hand": "🤚", "raised_hand": "✋", "metal": "🤘",
  "spock_hand": "🖖", "right_hand": "🖐", "crossed_fingers": "🤞", "handshake": "🤝",
  "thumbs_up": "👍", "thumbs_down": "👎", "fist": "✊", "facepunch": "👊",
  "uppercut": "👊", "point_left": "👈", "point_right": "👉", "point_up": "👆",
  "point_down": "👇", "ok_hand": "👌", "pinching_hand": "🤏", "+1": "👍",
  "-1": "👎", "fist Raised": "✊", "punch": "👊", "left_facing_fist": "🤛",
  "right_facing_fist": "🤜", "clap": "👏", "writing_hand": "✍️", "nail_care": "💅",
  " selfie": "🤳", "muscle": "💪", " mechanical_arm": "🦾", "leg": "🦵", "foot": "🦶",
  "ear": "👂", "nose": "👃", "brain": "🧠", "eye": "👁", "eyes": "👀",
  "tongue": "👅", "lips": "👄", "baby": "👼", "baby_chick": "🐣", "hatching_chick": "🐣",
  "hatched_chick": "🐥", "chick": "🐥", "adult": "🧑", "child": "👶", "older_adult": "👴",
  "older_man": "👴", "older_woman": "👵", "man": "👨", "woman": "👩", "angel": "👼",
  "pregnant_woman": "🤰", "breast_feeding": "🤱", "baby_bottle": "🍼", "bowl_with_spoon": "🥣",
  "chopsticks": "🥢", "fork_and_knife": "🍴", "fork_knife_plate": "🍽", "soccer": "⚽",
  "basketball": "🏀", "football": "🏈", "baseball": "⚾", "tennis": "🎾",
  "volleyball": "🏐", "rugby_football": "🏉", "trophy": "🏆", "medal": "🏅",
  "military_medal": "🎖", "1st_place_medal": "🥇", "2nd_place_medal": "🥈",
  "3rd_place_medal": "🥉", "cricket_bat_and_ball": "🏏", "ski": "🎿", "skier": "⛷",
  "skier2": "⛷", "snowboarder": "🏂", "snowboarder2": "🏂", "person_surfing": "🏄",
  "surfer": "🏄", "swimmer": "🏊", "swimmer2": "🏊", "person_playing_water_polo": "🤽",
  "water_polo": "🤽", "person_playing_handball": "🤾", "handball": "🤾",
  "person_ballet_dancing": "💃", "dancer": "💃", "people_wrestling": "🤼",
  "wrestlers": "🤼", "person_cartwheeling": "🤸", "cartwheel": "🤸",
  "person_bouncing_ball": "⛹", "basketball_player": "⛹", "person_lifting_weights": "🏋",
  "weight_lifter": "🏋", "fencer": "🤺", "person_juggling": "🤹", "juggling": "🤹",
  "horse_racing": "🏇", "boxing_glove": "🥊", "boxing_gloves": "🥊", "martial_arts_uniform": "🥋",
  "karate_uniform": "🥋", "crown": "👑", "queen": "👑", "wolf": "🐺", "wolf2": "🐺",
  "frog": "🐸", "tiger": "🐯", "tiger2": "🐯", "buffalo": "🦬", "ox": "🐂",
  "water_buffalo": "🐃", "cow": "🐄", "pig": "🐖", "pig2": "🐖", "mouse": "🐭",
  "mouse2": "🐭", "hamster": "🐹", "rabbit": "🐰", "rabbit2": "🐰", "bear": "🐻",
  "panda_face": "🐼", "koala": "🐨", "chipmunk": "🐿", "paw_prints": "🐾",
  "chicken": "🐔", "penguin": "🐧", "bird": "🐦", "hatching_chick": "🐣",
  "baby_chick": "🐥", "hatched_chick": "🐥", "duck": "🦆", "eagle": "🦅",
  "owl": "🦉", "bat": "🦇", "wolf3": "🐺", "boar": "🐗", "horse": "🐴",
  "unicorn": "🦄", "bee": "🐝", "bug": "🐛", "snail": "🐌", "ladybug": "🐞",
  "ant": "🐜", "spider": "🕷", "scorpion": "🦂", "crab": "🦀", "shrimp": "🦐",
  "lobster": "🦞", "oyster": "🦪", "squid": "🦑", "octopus": "🐙", "snake": "🐍",
  "turtle": "🐢", "crocodile": "🐊", "whale": "🐋", "whale2": "🐋", "dolphin": "🐬",
  "fish": "🐟", "tropical_fish": "🐠", "blowfish": "🐡", "jellyfish": "🪼",
  "shell": "🐚", "starfish": "🪨", "tropical_fish2": "🐠", "dolphin2": "🐬",
  "whale3": "🐳", "dragon": "🐉", "dragon_face": "🐲", "crocodile2": "🐊",
  "leopard": "🐆", "tiger3": "🐅", "zap": "⚡", "fire": "🔥", "flame": "🔥",
  "fire_spark": "🔥", "lightning": "⚡", "bolt": "⚡", "sunny": "☀️",
  "sun_with_face": "🌞", "sun": "☀️", "rainbow": "🌈", "cloud": "☁️",
  "cloud_with_rain": "🌧️", "cloud_with_lightning_and_rain": "⛈️", "sun_behind_cloud": "⛅",
  "thunder_cloud_and_rain": "⛈️", "sun_behind_rain_cloud": "🌦️", "cloud_with_snow": "🌨️",
  "cloud_with_lightning": "🌩️", "tornado": "🌪️", "fog": "🌫️", "wind_blowing_face": "🌬️",
  "umbrella": "☂️", "umbrella2": "☔", "droplet": "💧", "sweat_drops2": "💦",
  "water_wave": "🌊", "wave2": "🌊", "dash2": "💨", "snowflake": "❄️",
  "snowman": "⛄", "snowman2": "⛄", "snowman_without_snow": "⛅", "black_small_square": "▪️",
  "white_small_square": "▫️", "black_medium_square": "◼️", "white_medium_square": "◻️",
  "black_large_square": "⬛", "white_large_square": "⬜", "star": "⭐", "star2": "⭐",
  "sparkles": "✨", "dizzy": "💫", "collision": "💥", "boom": "💥",
  "explosion": "💥", "anger": "💢", "sweat": "😓", "droplets": "💧", "poop2": "💩",
  "shit": "💩", "muscle2": "💪", "clown": "🤡", "cowboy": "🤠", "smiley_cat": "😺",
  "smile_cat": "😸", "joy_cat": "😹", "heart_eyes_cat": "😻", "smirk_cat": "😼",
  "scream_cat": "🙀", "crying_cat_face": "😿", "pouting_cat": "😾", "see_no_evil": "🙈",
  "hear_no_evil": "🙉", "speak_no_evil": "🙊", "love_letter": "💌",
  "heart": "❤️", "green_heart": "💚", "blue_heart": "💙", "purple_heart": "💜",
  "yellow_heart": "💛", "orange_heart": "🧡", "black_heart": "🖤", "white_heart": "🤍",
  "brown_heart": "🤎", "broken_heart": "💔", "heart_exclamation": "❣️", "two_hearts": "💕",
  "revolving_hearts": "💞", "heartbeat": "💗", "pulse": "💗", "heartpulse": "💗",
  "cupid": "💘", "gift_heart": "💝", "sparkling_heart": "💖", "heartpulse2": "💖",
  "gift": "🎁", "tada": "🎉", "confetti_ball": "🎊", "balloon": "🎈",
  "ribbon": "🎀", "gift_box": "🎁", "christmas_tree": "🎄", "christmas": "🎄",
  "santa": "🎅", "mrs_claus": "🤶", "fireworks": "🎆", "sparkler": "✨",
  "firework": "🎆", "moon": "🌙", "new_moon": "🌑", "waxing_crescent_moon": "🌙",
  "first_quarter_moon": "🌓", "waxing_gibbous_moon": "🌔", "full_moon": "🌕",
  "gibbous_moon": "🌔", "last_quarter_moon": "🌗", "waning_crescent_moon": "🌘",
  "waning_gibbous_moon": "🌖", "crescent_moon": "🌙", "new_moon_with_star": "🌑",
  "moon_with_face": "🌝", "full_moon_with_face": "🌕", "sun_with_face2": "🌞",
  "first_quarter_moon_with_face": "🌓", "last_quarter_moon_with_face": "🌗",
  "moon_crescent": "🌙", "first_quarter_moon2": "🌓", "full_moon2": "🌕",
  "last_quarter_moon2": "🌗", "black_nib": "✒️", "pen": "🖊️", "pencil2": "✏️",
  "pencil": "✏️", "crayon": "🖍️", "paintbrush": "🖌️", "pen_fountain": "🖋️",
  "memo": "📝", "pencil2": "✏️", "briefcase": "💼", "file_folder": "📁",
  "folder": "📁", "open_file_folder": "📂", "page_facing_up": "📄", "page": "📄",
  "page_with_curl": "📃", "page_facing_up2": "📄", "page_with_curl2": "📃",
  "calendar": "📅", "tear_off_calendar": "📆", "calendar2": "📅", "notebook": "📓",
  "notebook_with_decorative_cover": "📔", "closed_book": "📕", "book": "📖",
  "open_book": "📖", "green_book": "📗", "blue_book": "📘", "orange_book": "📙",
  "books": "📚", "bookmark": "🔖", "bookmark_tabs": "📑", "label": "🏷️",
  "money_with_wings": "💸", "dollar": "💵", "money": "💰", "yen": "💴",
  "euro": "💶", "pound": "💷", "dollar2": "💵", "credit_card": "💳",
  "money_mouth_face": "🤑", "computer": "💻", "desktop_computer": "🖥️", "keyboard": "⌨️",
  "minidisc": "💽", "floppy_disk": "💾", "cd": "💿", "dvd": "📀", "vhs": "📼",
  "camera": "📷", "camera2": "📸", "video_camera": "📹", "tv": "📺",
  "phone": "📱", "telephone": "📞", "phone2": "📱", "telephone_receiver": "📞",
  "pager": "📟", "fax": "📠", "radio": "📻", "vibration_mode": "📳",
  "mobile_phone_off": "📴", "satellite": "🛰️", "megaphone": "📣",
  "mega": "📢", "outbox_tray": "📤", "inbox_tray": "📥", "package": "📦",
  "e-mail": "📧", "inbox": "📥", "envelope": "✉️", "email": "✉️",
  "envelope_with_arrow": "📩", "incoming_envelope": "📨", "envelope_with_arrow2": "📩",
  "love_letter2": "💌", "postal_horn": "📯", "postbox": "📮", "mailbox": "📫",
  "mailbox_closed": "📪", "mailbox_with_mail": "📬", "mailbox_with_no_mail": "📪",
  "door": "🚪", "door2": "🚪", "room": "🚪", "toilet": "🚽", "wc": "🚾",
  "bathtub": "🛁", "shower": "🚿", "bath": "🛀", "bath2": "🛀", "soap": "🧼",
  "bottle_with_popup": "🧪", "pill": "💊", "syringe": "💉", "dna": "🧬",
  "microbe": "🦠", "microscope": "🔬", "telescope": "🔭", "chart": "📈",
  "chart_with_upwards_trend": "📈", "chart_with_downwards_trend": "📉",
  "bar_chart": "📊", "clipboard": "📋", "calendar2": "📅", "calendar3": "📆",
  "spiral_calendar": "🗓️", "spiral_notepad": "🗒️", "pushpin": "📌", "pushpin2": "📍",
  "round_pushpin": "📍", "paperclip": "📎", "paperclip2": "📎", "straight_ruler": "📏",
  "triangular_ruler": "📐", "scissors": "✂️", "pencil2": "✏️", "blue_book2": "📘",
  "orange_book2": "📙", "notebook2": "📓", "ledger": "📒", "orange_book3": "📙",
  "closed_book2": "📕", "green_book2": "📗", "books2": "📚", "book2": "📖",
  "open_book2": "📖", "link": "🔗", "chain": "⛓️", "chains": "🔗",
  "paperclip3": "📎", "minidisc2": "💽", "floppy_disk2": "💾", "gear": "⚙️",
  "gear2": "⚙️", "toolbox": "🧰", "wrench": "🔧", "hammer": "🔨",
  "hammer_and_pick": "🔨", "pick": "⛏️", "hammer_and_wrench": "🛠️",
  "dagger": "🗡️", "crossed_swords": "⚔️", "shield": "🛡️", "wrench2": "🔧",
  "compression": "🗜️", "nut_and_bolt": "🔩", "key": "🔑", "old_key": "🗝️",
  "key2": "🔐", "lock": "🔒", "unlock": "🔓", "lock2": "🔒", "unlock2": "🔓",
  "bell": "🔔", "bell_with_slash": "🔕", "no_bell": "🔕", "bell2": "🔔",
  "megaphone2": "📢", "megaphone3": "📣", "speaker": "🔊", "speaker2": "🔈",
  "mute": "🔈", "speaker3": "🔊", "sound": "🔊", "loud_sound": "🔊",
  "no_mobile_phones": "📵", "no_mobile_phones2": "📴", "mobile_phone": "📱",
  "iphone": "📱", "calling": "📞", "mobile_phone2": "📱", "signal_strength": "📶",
  "arrows_clockwise": "🔄", "arrows_counterclockwise": "🔄", "low_brightness": "🔅",
  "high_brightness": "🔆", "magnet": "🧲", "warning": "⚠️", "warning2": "⚠️",
  "no_entry": "⛔", "no_entry_sign": "⛔", "name_badge": "📛", "prohibited": "🚫",
  "no_pedestrians": "⛔", "no_one_under_eighteen": "🔞", "non-potable_water": "🚱",
  "no_bicycles": "🚳", "cars": "🚗", "automobile": "🚗", "taxi": "🚕",
  "ambulance": "🚑", "fire_engine": "🚒", "police_car": "🚓", "bus": "🚌",
  "oncoming_bus": "🚍", "trolleybus": "🚎", "minibus": "🚐", "ambulance2": "🚑",
  "oncoming_police_car": "🚔", "oncoming_taxi": "🚖", "car2": "🚗", "taxi2": "🚕",
  "oncoming_automobile": "🚘", "fire_engine2": "🚒", "police_car2": "🚓", "bus2": "🚌",
  "oncoming_bus2": "🚍", "trolleybus2": "🚎", "ambulance3": "🚑", "tram": "🚊",
  "train": "🚃", "monorail": "🚝", "metropolitan": "🚇", "train2": "🚋",
  "light_rail": "🚈", "tram2": "🚊", "railway_car": "🚃", "tram_car": "🚊",
  "oncoming_monorail": "🚝", "oncoming_tram": "🚊", "railway_track": "🛤️",
  "tram_track": "🛤️", "metro": "🚇", "station": "🚉", "helicopter": "🚁",
  "airplane": "✈️", "airplane_departure": "🛫", "airplane_arriving": "🛬",
  "airplane2": "✈️", "oncoming_airplane": "✈️", "sailboat": "⛵", "boat": "⛵",
  "sailboat2": "⛵", "speedboat": "🚤", "ship": "🚢", "ship2": "🚢",
  "anchor": "⚓", "anchor2": "⚓", "hook": "🪝", "watch": "⌚",
  "hourglass": "⌛", "hourglass_flowing_sand": "⏳", "alarm_clock": "⏰",
  "stopwatch": "⏱️", "timer": "⏲️", "clock": "🕐", "clock2": "🕐",
  "clock3": "🕑", "clock4": "🕒", "clock5": "🕓", "clock6": "🕔",
  "clock7": "🕕", "clock8": "🕖", "clock9": "🕗", "clock10": "🕘",
  "clock11": "🕙", "clock12": "🕚", "compass": "🧭", "globe_with_meridians": "🌐",
  "earth_americas": "🌎", "earth_africa": "🌍", "earth_asia": "🌏",
  "globe": "🌍", "world_map": "🗺", "japan": "🗾", "mount_fuji": "🗻",
  "moyai": "🗿", "statue_of_liberty": "🗽", "tokyo_tower": "🗼", "bridge": "🌉",
  "fountain": "⛲", "foggy": "🌁", "city_sunset": "🌆", "city_sunrise": "🌇",
  "sunset": "🌇", "sunrise": "🌅", "rainbow2": "🌈", "bridge_at_night": "🌉",
  "fountains": "⛲", "night_with_stars": "🌃", "sunrise_over_mountains": "🌄",
  "cityscape": "🌆", "citysunset": "🌇", "sunset2": "🌇", "stars": "🌃",
  "milky_way": "🌌", "sparkle2": "✨", "flipped": "🙃", "upside_down": "🙃",
  "shrug": "🤷", "thinking": "🤔", "expressionless": "😑", "neutral_face": "😐",
  "no_good": "🙅", "ok_woman": "🙆", "bow": "🙇", "man_tipping_hand": "💁",
  "person_tipping_hand": "💁", "older_man2": "👴", "older_woman2": "👵",
  "man_with_gua_pi_mao": "👲", "woman_with_turban": "👳", "man_with_turban": "👳",
  "police_officer": "👮", "angel2": "👼", "princess": "👸", "guardsman": "💂",
  "prince": "🤴", "construction_worker": "👷", "baby_angel": "👼", "bride_with_veil": "👰",
  "man_in_tuxedo": "🤵", "person_with_blond_hair": "👱", "person_frowning": "🙍",
  "person_with_pouting_face": "🙎", "person_bowing": "🙇", "sassy": "💁",
  "footprints": "👣", "footprint": "👣", "tipping_hand_man": "💁",
  "tipping_hand_woman": "💁", "santa2": "🎅", "mrs_claus2": "🤶",
  "santa_mrs": "🤶", "mother_christmas": "🤶", "person_gesturing_no": "🙅",
  "person_gesturing_ok": "🙆", "person-raising-hand": "🤚", "raising-hand": "✋",
  "raised-hand": "✋", "deaf_person": "🧏", "deaf_man": "🧏‍♂️", "deaf_woman": "🧏‍♀️",
  "couple_with_heart": "💑", "couple_with_heart_woman_man": "💑", "couple_ww": "👩‍❤️‍👩",
  "couple_mm": "👨‍❤️‍👨", "family": "👨‍👩‍👧", "family_man_woman_girl": "👨‍👩‍👧",
  "family_mwg": "👨‍👩‍👦", "family_mwbb": "👨‍👩‍👶", "family_mwg_girl": "👨‍👩‍👧",
  "family_mwg_boy": "👨‍👩‍👦", "family_mwg_girl_boy": "👨‍👩‍👧👦", "family_mwbb_boy": "👨‍👩‍👶👦",
  "family_mwbb_girl": "👨‍👩‍👶👧", "couple_with_heart2": "💑", "family_wwb": "👩‍👩‍👦",
  "family_wwg": "👩‍👩‍👧", "family_wwgb": "👩‍👩‍👧👦", "family_wwbb": "👩‍👩‍👶",
  "family_wwg_boy": "👩‍👩‍👧👦", "family_mmb": "👨‍👨‍��", "family_mmg": "👨‍👨‍👧",
  "family_mmg_boy": "👨‍👨‍👧👦", "family_mmg_girl": "👨‍👨‍👧👧", "family_mm_gb": "👨‍👨👦",
  "family_mm_g": "👨‍👨👧", "family_mm_gb_girl": "👨‍👨👦👧", "couplekiss": "💏",
  "kiss_ww": "👩‍❤️‍💋‍👩", "kiss_mm": "👨‍❤️‍💋‍👨", "kiss_woman_man": "💏",
  "footprints2": "👣", "bust": "👤", "busts_in_silhouette": "👤",
  "bust_in_silhouette": "👤", "busts_in_silhouette2": "👥", "people_holding_hands": "👭",
  "two_women_holding_hands": "👭", "two_men_holding_hands": "👬",
  "men_holding_hands": "👬", "women_holding_hands": "👭", "walking": "🚶",
  "person_walking": "🚶", "walking2": "🚶", "runner": "🏃", "person_running": "🏃",
  "running": "🏃", "dancer2": "💃", "man_dancing": "💃", "dancing2": "💃",
  "couple": "👯", "walking_woman": "🚶‍♀️", "walking_man": "🚶‍♂️",
  "running_woman": "🏃‍♀️", "running_man": "🏃‍♂️", "woman_walking": "🚶‍♀️",
  "man_walking": "🚶‍♂️", "woman_running": "🏃‍♀️", "man_running": "🏃‍♂️",
  "joggers": "🏃", "jogger": "🏃", "jogging": "🏃", "couplekiss2": "💏",
  "kiss2": "💋", "kiss_lips": "💋", "beating_heart": "💗", "heart_decoration": "💟",
  "heart_circle": "🧡", "heart_on": "💖", "growing_heart": "💕", "two_arrow_circle": "🔃",
  "arrow_heading_up": "⭝", "arrow_heading_down": "⭝", "arrow_heading_down2": "⭟",
  "arrow_up": "⬆️", "arrow_down": "⬇️", "arrow_up2": "⬆️", "arrow_down2": "⬇️",
  "left_right_arrow": "↔️", "leftwards_arrow": "←️", "arrow_right": "➡️",
  "up_down_arrow": "↕️", "upwards_arrow": "⬆️", "downwards_arrow": "⬇️",
  "arrow_right_hook": "↩️", "leftwards_arrow_hook": "↩️", "arrow_left": "←️",
  "arrow_right2": "➡️", "leftwards_long_arrow": "⟵", "rightwards_long_arrow": "⟶",
  "arrow_left_right": "↔️", "arrow_up_down": "↕️", "curly_loop": "➰",
  "loop": "➰", "arrows_cycled": "🔄", "clockwise": "🔁", "arrow_counterclockwise": "↩️",
  "arrow_backward": "↩️", "arrow_forward": "➡️", "arrow_double_up": "⏫",
  "arrow_double_down": "⏬", "arrow_double_up2": "⏫", "arrow_double_down2": "⏬",
  "double_vertical_bar": "⏸", "play_pause": "⏯", "play": "▶️", "pause": "⏸",
  "play2": "▶", "pause2": "⏸", "stop": "⏹", "stop_button": "⏹",
  "record": "⏺", "eject": "⏏", "eject2": "⏏", "last_track_button": "⏮",
  "fast_forward": "⏩", "fast_reverse": "⏪", "fast_forward2": "⏩",
  "fast_reverse2": "⏪", "next_track": "⏭", "previous_track": "⏮",
  "track_next": "⏭", "track_previous": "⏮", "twisted_rightwards_arrows": "🔀",
  "shuffle": "🔀", "repeat": "🔁", "repeat_one": "🔂", "repeat_one2": "🔂",
  "repeat2": "🔁", "low_volume": "🔈", "medium_volume": "🔉", "high_volume": "🔊",
  "speaker_low_volume": "🔈", "speaker_medium_volume": "🔉", "speaker_high_volume": "🔊",
  "speaker_muted": "🔇", "mute2": "🔇", "unmuted": "🔈", "muted": "🔇",
  "bells": "🔔", "bell2": "🔔", "bell_accent": "🔕", "bell_with_slash2": "🔕",
  "no_bell2": "🔕", "musical_note": "🎵", "musical_notes": "🎵",
  "note": "🎵", "notes": "🎶", "musical_score": "🎼", "musical_keyboard": "🎹",
  "guitar": "🎸", "trumpet": "🎺", "violin": "🎻", "saxophone": "🎷",
  "drum": "🥁", "drum_with_drumsticks": "🥁", "drum2": "🎵", "cl": "🫡",
  "cool": "😎", "free": "🆓", "information_source": "ℹ️", "id": "🆔",
  "ideograph_advantage": "🉐", "abc": "🔤", "abcd": "🔤", "cap": "🧢",
  "clown_face": "🤡", "cn": "🇨🇳", "computer": "💻", "congratulations": "㊗️",
  "cool2": "🆒", "copyright": "©️", "credit_card2": "💳", "currency_exchange": "💱",
  "customs": "🛃", "diamond_shape_with_dot_inside": "💠", "dna2": "🧬",
  "dog": "🐶", "dollar2": "💲", "dvd2": "📀", "edit": "✏️", "eight": "8️⃣",
  "eight_pointed_black_star": "✴️", "eight_spoked_asterisk": "✳️", "eject2": "⏏",
  "envelope": "✉️", "euro2": "💶", "exclamation": "❗️", "eyes": "👀",
  "file_folder2": "📁", "fist2": "✊", "five": "5️⃣", "floppy_disk2": "💾",
  "flower_playing_cards": "🃏", "flushed2": "😳", "free2": "🆓",
  "fuelpump": "⛽", "full_moon": "🌕", "game_die": "🎲", "gem": "💎",
  "girl": "👧", "globe_with_leads": "🌐", "goat": "🐐", "hammer2": "🔨",
  "hash": "#️⃣", "hatched_chick2": "🐥", "heavy_dollar_sign": "💲",
  "hedge_hedge": "🍇", "helmet": "⛑️", "helmet_with_cross": "⛑️",
  "honey_pot": "🍯", "hotsprings": "♨️", "hourglass2": "⌛", "hundred": "💯",
  "ideograph_secret": "㊙️", "ideograph_advantage2": "🉐", "imp": "😈",
  "inbox_tray": "📥", "incoming_envelope": "📨", "information": "ℹ️",
  "interrobang": "⁉️", "jack_o_lantern": "🎃", "japan": "🗾", "jeans": "👖",
  "joy_cat2": "😹", "key2": "🔑", "keycap_ten": "🔟", "kimono": "👘",
  "kiss2": "💋", "kobe": "🍜", "legs": "🦵", "lens": "📷", "leopord": "🐆",
  "libra": "⚖️", "man": "👨", "man_with_gua_pi_mao2": "👲", "man_with_turban2": "👳",
  "maple_leaf": "🍁", "mapp": "🗺️", "mask": "😷", "mask2": "😷",
  "meat_on_bone": "🍖", "medal2": "��", "mega2": "📢", "mermaid": "🧜‍♀️",
  "merman": "🧜‍♂️", "metro2": "🚇", "microphone": "🎤", "microscope2": "🔬",
  "middle_finger": "🖕", "military_ribbon": "🎖", "milky_way2": "🌌", "minibus2": "🚐",
  "minidisc": "💽", "minus": "➖", "mobile_phone2": "📱", "moneys": "💸",
  "nail_polish": "💅", "national_park": "🏞️", "necktie": "👔", "necktie2": "👔",
  "negative_squared_cross_mark": "❎", "new": "🆕", "new_moon": "🌑", "ng": "🆖",
  "nine": "9️⃣", "no_bell2": "🔕", "no_entry_sign2": "⛔", "no_mobile_phones": "📵",
  "no_pedestrians2": "⛔", "non-potable_water": "🚱", "nose": "👃", "notebook2": "📓",
  "notes2": "🎶", "number_tab": "🔢", "nuts": "🥜", "office": "🏢",
  "offended": "😖", "older_man": "👴", "older_woman": "👵", "om": "🕉️",
  "one": "1️⃣", "one_hundred": "💯", "one_thirty": "🕐", "one_two": "🕐",
  "open_hands": "👐", "optical_disk": "📀", "orange_book": "📙", "outbox": "📤",
  "ox2": "牛", "package2": "📦", "page": "📄", "page_facing_up": "📄",
  "page_with_curl": "📃", "pager": "📟", "palms": "👐", "park": "🏞️",
  "parking": "🅿️", "part_alternation_mark": "〽️", "passport_control": "🛂",
  "paw_prints2": "🐾", "peach": "🍑", "peanuts": "🥜", "pedestrian": "🚶",
  "pen2": "🖊️", "pencil": "✏️", "pensive": "😔", "pensive2": "😔",
  "performing_arts": "🎭", "persevering": "😣", "person_fencing": "🤺", "peter": "🍐",
  "petri_dish": "🧫", "pick2": "⛏️", "pie": "🥧", "pig2": "🐖",
  "pilot": "👨‍✈️", "pince_nez": "👓", "pineapple": "🍍", "ping_pong": "🏓",
  "pisces": "♓️", "pizza": "🍕", "place": "🗺️", "plate": "🍽️", "play": "▶️",
  "plus": "➕", "poop": "💩", "poodle": "🐩", "popcorn": "🍿", "post_office": "🏣",
  "postbox": "📮", "potable": "🚰", "potable_water": "🚰", "pouch": "👛",
  "poultry_leg": "🍗", "pound": "💷", "pound2": "💷", "pout": "�嘟",
  "pouting": "😡", "pray": "🙏", "prayer": "🙏", "pregnant2": "🤰",
  "principal": "🎓️", "printer": "🖨️", "purple_heart": "💜", "purse": "👛",
  "pushpin": "📌", "puzzle": "🧩", "question": "❓", "rabbit2": "🐰",
  "racial": "👊", "racing_car": "🏎️", "racing_motorcycle": "🏍️", "racehorse": "🐴",
  "radar": "📡", "radio2": "📻", "rage": "😡", "rage1": "😡", "raging": "😡",
  "rainbow": "🌈", "rainbow_flag": "🏳️‍🌈", "raised_back": "🤚", "raised_hands": "🙏",
  "raising": "���", "ram": "🐏", "ramen": "🍜", "rat": "🐀", "record2": "⏺",
  "recycle": "♻️", "red_car": "🚗", "red_circle": "🔴", "registered": "®️",
  "repeat": "🔁", "restroom": "🚾", "revolver": "🔫", "revolving": "💞",
  "ribbon2": "🎀", "rice": "🍚", "rice_ball": "🍙", "rice_cracker": "🍘",
  "rice_scene": "🎎", "ring": "💍", "ringed_planet": "🪐", "robot": "🤖",
  "rock": "🪨", "rocket": "🚀", "rofl2": "🤣", "romance": "💐", "rooster": "🐓",
  "rose": "🌹", "rosette": "🏵️", "rotating_light": "🚨", "round_checkmark": "✅",
  "rowboat": "🚣", "rugby": "🏉", "runner2": "🏃", "running2": "🏃",
  "russian": "🇷🇺", "sailboat": "⛵", "sakura": "🌸", "salt": "🧂",
  "samp": "🥣", "sandal": "👡", "santa": "🎅", "saturn": "🪐", "sauce": "🍲",
  "sauna": "🧖", "sausage": "🌭", "scales": "⚖️", "school": "🏫",
  "school_satchel": "🎒", "scissors2": "✂️", "scorpio": "♏️", "scorpion": "🦂",
  "scream": "😱", "scream_cat": "🙀", "scroll": "📜", "seat": "💺",
  "second_place": "🥈", "secret": "㊙️", "see_no_evil": "🙈", " seedling": "🌱",
  "seven": "7️⃣", "shallow": "🥣", "shame": "🫣", "shaved_ice": "🍧",
  "shield2": "🛡️", "shinto_shrine": "⛩️", "ship2": "🚢", "shirt": "👕",
  "shit2": "💩", "shoe": "👟", "shooting_star": "🌠", "shopping_bags": "🛍️",
  "shortcake": "🍰", "shower2": "🚿", "shrimp2": "🦐", "shrug2": "🤷",
  "sick": "🤢", "sign_of_the_horns": "🤘", "sikh": "🧕", "silence": "🔇",
  "singer": "🎤", "sintab": "🧂", "six": "6️⃣", "six_pointed_star": "🔯",
  "ski": "🎿", "skin-tone": "🟖", "skull": "💀", "slayer": "💀",
  "sleeping": "😴", "sleepy": "😪", "slightly_frowning": "🙁", "slightly_smiling": "🙂",
  "slot_machine": "🎰", "small_blue_diamond": "🔹", "small_orange_diamond": "🔸",
  "small_red_triangle": "🔺", "small_red_triangle_down": "🔻", "smile2": "😄",
  "smile_cat": "😸", "smiling_imp": "😈", "smirk2": "😏", "smoke": "💨",
  "snake": "🐍", "sneaker": "👟", "snowboard": "🏂", "snowflake2": "❄️",
  "soba": "🍜", "soccer2": "⚽", "socks": "🧦", "sofa": "🛋️",
  "softball": "⚾", "soon": "🔜", "sore_throat": "😷", "sos": "🆘",
  "sound2": "🔊", "soup": "🥣", "sparkle": "✨", "sparkler": "🎆",
  "sparkles2": "✨", "speaker": "🔈", "speaking_head": "🗣️", "speech_balloon": "💬",
  "speech_left": "💬", "speedboat": "🚤", "spider_web": "🕸️", "spiral_calendar_pad": "🗓",
  "spiral_notepad": "🗒", "spoon": "🥄", "sportUtility": "🚙", "sports_medal": "🏅",
  "spot": "🈁", "spray": "🧴", "squeezy": "🥑", "squirrel": "🐿️",
  "stadium": "🏟️", "star2": "⭐", "star_and_crescent": "☪️", "stars": "🌟",
  "station2": "🚉", "statue": "🗽", "steam_locomotive": "🚂", "steam": "🧖",
  "stew": "🍲", "stop": "🛑", "stop_button2": "⏹", "stopper": "🛑",
  "straight_ruler2": "📏", "strawberry": "🍓", "streetcar": "🚊", "stuck_out": "😜",
  "studio_microphone": "🎙️", "stuffed_pasta": "🍝", "stumbler": "🤢", "subdirectory": "📂",
  "sunflower": "🌻", "sunny2": "☀️", "sunrise2": "🌅", "sunset": "🌇",
  "superhero": "🦸", "supervillain": "🦹", "sushi": "🍣", "suspect": "🕵️",
  "sweat": "😥", "sweat1": "💦", "sweat2": "😓", "sweet_potato": "🍠",
  "swim": "🏊", "swimmer2": "🏊", "symbol": "🈂", "syringe2": "💉",
  "taco": "🌮", "tada": "🎉", "takeout_box": "🥡", "tako": "🐙",
  "tamale": "🥟", "tangerine": "🍊", "taureau": "牛", "taxi2": "🚕",
  "tea": "☕", "teacher": "🧑‍🏫", "teapot": "🫖", "team": "🧑‍🤝‍🧑",
  "technologist": "🧑‍💻", "telephone2": "☎️", "telescope2": "🔭", "tennis2": "🎾",
  "tent": "⛺", "tent2": "⛺", "the_horns": "🤘", "thinking2": "🤔",
  "thought_balloon": "💭", "threed": "📱", "three": "3️⃣", "thumbs_down2": "👎",
  "thumbs_up2": "👍", "thunder": "⚡", "thunder_cloud": "🌩️", "ticket": "🎫",
  "ticket2": "🎟️", "tiger": "🐅", "timer2": "⏲️", "tired2": "😩",
  "tm": "™️", "toilet": "🚽", "tokyo_tower": "🗼", "tomato": "🍅",
  "tongue2": "👅", "tools": "🧰", "tooth": "🦷", "top": "🔝",
  "top_hat": "🎩", "tophat": "🎩", "tornado2": "🌪️", "tortoise": "🐢",
  "tote": "👜", "touch": "🤚", "toward": "🧭", "towel": "🧖",
  "tower": "🗼", "town": "🏣", "tox": "🧬", "toystore": "🛒", "tr": "🇹🇷",
  "track": "🛤️", "tractor": "🚜", "traffic_light": "🚥", "trailer": "🚍",
  "train2": "🚃", "tram2": "🚊", "treasure": "💎", "tree": "🌳", "tree2": "🌲",
  "triangular_ruler2": "📐", "trident": "🔱", "trollface": "🧌", "trophy2": "🏆",
  "tropical_drink": "🍹", "truck": "🚚", "trumpet2": "🎺", "tulsi": "🪴",
  "turkey": "🦃", "turn": "➰", "turquoise": "🧉", "turtle2": "🐢",
  "tv2": "📺", "twisted": "➰", "two": "2️⃣", "two_men_holding": "👬",
  "two_women_holding": "👭", "two_hearts2": "💕", "typing": "🗣️",
  "umbrella2": "☔", "umbrella3": "☂️", "unamused": "😒", "octocat": "🐙",
  "oden": "🍢", "office2": "🏢", "oil": "🛢️", "old_key2": "🗝️",
  "old_man": "👴", "old_woman": "👵", "on": "🔛", "one_three": "🕐",
  "one_two_three": "🕐", "onion": "🧅", "open_file_folder": "📂",
  "open_hands2": "👐", "orange_book2": "📙", "orange_heart": "🧡", "ornament": "🎄",
  "otter": "🦦", "outbox_tray": "📤", "owl2": "🦉", "oyster2": "🦪",
  "package": "📦", "pager2": "📟", "page_facing_up": "📄", "page_with_curl": "📃"
};

window.EMOJI_CATEGORIES = {
  "smileys": {
    "name": "Smileys",
    "icon": "😃",
    "emojis": [
      "grinning", "grimacing", "grin", "joy", "rofl", "sweat_smile", "laughing", "innocent",
      "smiling_imp", "sunglasses", "monkey_face", "cat", "smirk", "cat_face_with_wry_smile",
      "kissing_cat", "scream_cat", "crying_cat", "pouting_cat", "joy_cat", "heart_eyes_cat",
      "smirk_cat", "blue_heart", "brown_heart", "white_heart", "heart_eyes", "kissing_heart",
      "kissing_cat", "heart_on_fire", "mending_heart", "red_heart", "purple_heart",
      "orange_heart", "green_heart", "yellow_heart", "kiss", "smile", "sweat", "smile2",
      "laugh", "wink", "blush", "sleepy", "relieved", "stuck_out_tongue_winking_eye",
      "stuck_out_tongue_closed_eyes", "stuck_out_tongue", "sunglasses", "dizzy", "worried",
      "astonished", "frowning", "anguished", "hushed", "flushed", "pensive", "sob",
      "cry", "disappointed", "confounded", "dizzy_face", "tired_face", "face_exhaling",
      "woozy_face", "drooling_face", "sleeping", "mask", "face_with_thermometer",
      "face_with_head_bandage", "nauseated_face", "face_vomiting", "sneezing_face",
      "hot_face", "cold_face", "exploding_head", "confused", "worried_face_with_open_mouth",
      "astonished_face", "fearful_face", "anxious_face_with_sweat", "sad_relieved_face", "pouting_face",
      "angry_face", "face_with_steam_from_nose", "downcast_face_with_sweat", "sad_face",
      "anguished_face", "weary_face"
    ]
  },
  "gestures": {
    "name": "Gestures",
    "icon": "👋",
    "emojis": [
      "wave", "raised_back_of_hand", "raised_hand", " Vulcan", "spock_hand", "right_hand",
      "crossed_fingers", "handshake", "thumbs_up", "thumbs_down", "fist",
      "facepunch", "left_facing_fist", "right_facing_fist", "clap", "writing_hand",
      "nail_care", "selfie", "muscle", "mechanical_arm", "leg", "foot", "ear",
      "nose", "eye", "eyes", "tongue", "lips", "shaking_face", "hand_over_mouth",
      "saluting", "raising_hands", "OK_hand", "pinching_hand", "Index_pointing_At_The_Viewer"
    ]
  },
  "people": {
    "name": "People",
    "icon": "👤",
    "emojis": [
      "baby", "child", "person", "person_bearding", "blond_hair", "blonde_woman",
      "blond_man", "older_adult", "older_man", "older_woman", "man", "woman",
      "pregnant_woman", "breast_feeding", "angel", "baby_angel", "santa", "mrs_claus",
      "superhero", "supervillain", "mage", "fairy", "vampire", "merperson", "elf",
      " genie", "zombie", "person_in_tuxedo", "person_with_skullcap",
      "woman_with_headscarf", "man_with_beard", "older_person", "boy", "girl", "family"
    ]
  },
  "nature": {
    "name": "Animals",
    "icon": "🐱",
    "emojis": [
      "dog", "cat", "mouse", "hamster", "rabbit", "bear", "panda_face", "koala",
      "tiger", "wolf", "fox", "lion", "wolf_face", "leopard", "cat_face", "tiger2",
      "lion_face", "cow", "pig", "boar", "ox", "water_buffalo", "buffalo", "ram", "ewe",
      "goat", "rooster", "chicken", "penguin", "duck", "eagle", "owl", "bat", "bird",
      "hatching_chick", "baby_chick", "hatched_chick", "turkey", "dove", "rabbit_face",
      "rat", "snake", "dragon_face", "dragon", "crocodile", "whale", "whale2",
      "dolphin", "fish", "tropical_fish", "blowfish", "jellyfish", "octopus",
      "shell", "squid", "lobster", "shrimp", "crab", "frog", "turtle",
      "ladybug", "spider", "scorpion", "ant", "bee", "bug", "snail", "butterfly",
      "snail2", "worm", "spider_web"
    ]
  },
  "food": {
    "name": "Food",
    "icon": "🍕",
    "emojis": [
      "apple", "pear", "tangerine", "lemon", "banana", "watermelon", "grapes", "strawberry",
      "blueberries", "corn", "tomato", "potato", "carrot", "hot_pepper", "cucumber",
      "broccoli", "mushroom", "peanuts", "chestnut", "bread", "croissant", "baguette_bread",
      "pretzel", "pancakes", "waffle", "cheese", "meat_on_bone", "poultry_leg",
      "bacon", "sandwich", "taco", "burrito", "salad", "popcorn", "butter",
      "salt", "canned_food", "rice", "rice_cracker", "rice_ball", "curry", "ramen",
      "spaghetti", "oden", "sushi", "fried_shrimp", "fish_cake", "moon_cake",
      "dango", "doughnut", "cookie", "chocolate_bar", "candy", "lollipop",
      "ice_cream", "doughnut", "pie", "custard", "honey_pot", "baby_bottle",
      "milk", "bottle_with_popping_cork", "coffee", "tea", "cup_with_straw", "sake",
      "beer", "beers", "clinking_glasses", "wine_glass", "tumbler_glass", "cocktail",
      "tropical_drink", "mate", "beverage_box", "rice_scene", "bento", "curry_rice",
      "stew", "egg", "fried_egg", "shallow_pan_of_food", "pot_of_food", "bowl"
    ]
  },
  "activities": {
    "name": "Activities",
    "icon": "⚽",
    "emojis": [
      "soccer", "basketball", "football", "baseball", "tennis", "volleyball",
      "rugby_football", "trophy", "medal", "military_medal", "1st_place_medal",
      "2nd_place_medal", "3rd_place_medal", "sports_medal", "cricket_bat_and_ball",
      "ski", "skier", "snowboarder", "person_surfing", "surfer", "swimmer",
      "person_playing_water_polo", "person_playing_handball", "person_cartwheeling",
      "person_bouncing_ball", "person_lifting_weights", "weight_lifter", "fencer",
      "person_juggling", "horse_racing", "boxing_glove", "martial_arts_uniform",
      "badminton", "bow_and_arrow", "rowboat", "canoe", "rowing", "person_bowing",
      "tadoraiko", "instrument", "violin", "guitar", "saxophone", "trumpet",
      "piano", "musical_keyboard", "drum", "banjo", "game_die", "chess_pawn",
      "dart", "kite", "yo-yo", "jigsaw", "nazar_amulet", "performing_arts"
    ]
  },
  "travel": {
    "name": "Travel",
    "icon": "✈️",
    "emojis": [
      "rocket", "stars", "star", "sparkle", "fire", "comet", "rainbow",
      "hollow_black_circle", "white_circle", "red_circle", "blue_circle",
      "orange_circle", "yellow_circle", "green_circle", "purple_circle",
      "brown_circle", "red_cross", "white_cross", "star_and_crescent",
      "star_of_david", "peace", "yin_yang", "orthodox_cross", "cross",
      "wheel", "wheel_of_dharma", "f Symbols", "atom", "alien",
      "personal_computer", "minidisc", "floppy_disk", "cd", "dvd",
      "vhs", "camera", "video_camera", "tv", "phone", "telephone",
      "pager", "fax", "radio", "vibration_mode", "mobile_phone_off",
      "satellite", "megaphone", "outbox_tray", "inbox_tray", "package",
      "e-mail", "envelope", "envelope_with_arrow", "love_letter",
      "postal_horn", "postbox", "mailbox", "mailbox_closed", "mailbox_with_mail"
    ]
  },
  "objects": {
    "name": "Objects",
    "icon": "💡",
    "emojis": [
      "watch", "alarm_clock", "stopwatch", "timer", "hourglass", "hourglass_flowing_sand",
      "key", "old_key", "lock", "unlock", "lock_with_key", "pushpin", "pushpin2",
      "link", "chains", "paperclip", "paperclip2", "magnet", "toolbox", "wrench",
      "hammer", "hammer_and_pick", "pick", "hammer_and_wrench", "dagger",
      "crossed_swords", "shield", "nut_and_bolt", "gear", "gear2", "computer",
      "desktop_computer", "keyboard", "trash", "wastebasket", "litter_in_box",
      "cup_on_left", "cup_on_right", "binoculars", "shopping_trolley", "hammer2"
    ]
  },
  "symbols": {
    "name": "Symbols",
    "icon": "❤️",
    "emojis": [
      "heart", "heart_on_fire", "mending_heart", "heart_exclamation", "two_hearts", "revolving_hearts",
      "beating_heart", "growing_heart", "sparkling_heart", "cupid", "gift_heart",
      "heartpulse", "blue_heart", "green_heart", "yellow_heart", "purple_heart",
      "orange_heart", "broken_heart", "heavy_heart_exclamation", "heart_decoration",
      "black_heart", "white_heart", "restroom", "men", "women", "water_wave",
      "wheelchair", "potable_water", "no_entry", "no_entry_sign", "name_badge",
      "prohibited", "no_pedestrians", "no_one_under_eighteen", "non-potable_water",
      "no_bicycles", "no_smoking", "warning", "children_crossing", "radioactive",
      "biohazard", "trigram", "warning2", "ATM", "wc", "potable_water", "wheelchair2",
      "mens", "womens", "restroom2", "babies", "baby_symbol", "bath", "shower",
      "bathtub", "door", "toilet", "couch", "bed"
    ]
  },
  "flags": {
    "name": "Flags",
    "icon": "🏳️",
    "emojis": [
      "flag_white", "flag_black", "flag_tr", "flag_af", "flag_ax", "flag_al", "flag_dz", "flag_as",
      "flag_ad", "flag_ao", "flag_ai", "flag_aq", "flag_ag", "flag_ar", "flag_am", "flag_aw",
      "flag_au", "flag_at", "flag_az", "flag_bs", "flag_bh", "flag_bd", "flag_bb",
      "flag_by", "flag_be", "flag_bz", "flag_bj", "flag_bm", "flag_bo", "flag_bq",
      "flag_ba", "flag_bw", "flag_bv", "flag_br", "flag_io", "flag_vg", "flag_vi",
      "flag_bn", "flag_bg", "flag_bf", "flag_bi", "flag_kh", "flag_cm", "flag_ca",
      "flag_ic", "flag_cv", "flag_ky", "flag_cf", "flag_td", "flag_cl", "flag_cn",
      "flag_cx", "flag_cc", "flag_co", "flag_km", "flag_cg", "flag_cd", "flag_ck",
      "flag_cr", "flag_ci", "flag_hr", "flag_cu", "flag_cw", "flag_cy", "flag_cz",
      "flag_dk", "flag_dj", "flag_dm", "flag_do", "flag_dz", "flag_ec", "flag_eg",
      "flag_er", "flag_es", "flag_ee", "flag_et", "flag_eu", "flag_fk", "flag_fj",
      "flag_fi", "flag_fr", "flag_tf", "flag_ga", "flag_gm", "flag_ge", "flag_de",
      "flag_gh", "flag_gi", "flag_gr", "flag_gl", "flag_gd", "flag_gp", "flag_gu",
      "flag_gt", "flag_gg", "flag_gn", "flag_gw", "flag_gy", "flag_hk", "flag_hm",
      "flag_hn", "flag_hu", "flag_is", "flag_in", "flag_ir", "flag_iq", "flag_ie",
      "flag_im", "flag_il", "flag_it", "flag_jm", "flag_je", "flag_jo", "flag_kz",
      "flag_ke", "flag_ki", "flag_xk", "flag_kw", "flag_kg", "flag_la", "flag_lv",
      "flag_lb", "flag_ls", "flag_lr", "flag_ly", "flag_li", "flag_lt", "flag_lu",
      "flag_mo", "flag_mk", "flag_mg", "flag_mw", "flag_my", "flag_mv", "flag_ml",
      "flag_mt", "flag_mh", "flag_mq", "flag_mr", "flag_mu", "flag_yt", "flag_mx",
      "flag_fm", "flag_md", "flag_mc", "flag_mn", "flag_me", "flag_ms", "flag_ma",
      "flag_mz", "flag_mm", "flag_na", "flag_nr", "flag_np", "flag_nl", "flag_nc",
      "flag_nz", "flag_ni", "flag_ne", "flag_ng", "flag_nu", "flag_nf", "flag_kp",
      "flag_mp", "flag_no", "flag_om", "flag_pk", "flag_pw", "flag_ps", "flag_pa",
      "flag_pg", "flag_py", "flag_pe", "flag_ph", "flag_pn", "flag_pl", "flag_pt",
      "flag_pr", "flag_qa", "flag_re", "flag_ro", "flag_ru", "flag_rw", "flag_ws",
      "flag_sm", "flag_st", "flag_sa", "flag_sn", "flag_rs", "flag_sc", "flag_sl",
      "flag_sg", "flag_sx", "flag_sk", "flag_si", "flag_gs", "flag_so", "flag_zr",
      "flag_sd", "flag_se", "flag_ch", "flag_tw", "flag_tj", "flag_tz", "flag_th",
      "flag_tl", "flag_tg", "flag_tk", "flag_to", "flag_tt", "flag_tn", "flag_tr",
      "flag_tm", "flag_tc", "flag_tv", "flag_ug", "flag_ua", "flag_ae", "flag_gb",
      "flag_us", "flag_uy", "flag_uz", "flag_va", "flag_vc", "flag_ve", "flag_vn",
      "flag_vu", "flag_wf", "flag_eh", "flag_ye", "flag_zm", "flag_zw", "flag_ac",
      "flag_bq", "flag_ea", "flag_txa", "flag_sah", "flag_tas"
    ]
  }
};

window.EMOJI_SEARCH_ALIASES = {
  "smile": "grinning", "happy": "joy", "lol": "rofl", "lmao": "rofl",
  "happycry": "rofl", "rotfl": "rofl", "sweat": "sweat_smile",
  "laugh": "laughing", ":D": "grinning", ":D": "grinning",
  ";)": "wink", ":)": "smile", ":(": "slightly_frowning",
  ":'(": "cry", ":'))": "joy", "<3": "heart",
  ":*": "kiss", ";*": "kiss", ":p": "stuck_out_tongue",
  ":P": "stuck_out_tongue", "xp": "stuck_out_tongue_winking_eye",
  "XP": "stuck_out_tongue_winking_eye", ":d": "grinning",
  ":d": "grinning", "8)": "sunglasses", "8D": "sunglasses",
  ">:(": "angry", ">:(": "angry", ":@": "angry",
  "doge": "japanese_ogre", "kappa": "japanese_goblin",
  "poker": "neutral_face", "troll": "trollface",
  "feelsgood": "ok_woman", "feelsbad": "disappointed",
  "finnadie": "sunglasses", "god": "innocent", "allthethings": "star",
  "4ever": "abc", "octocat": "octocat", "shipit": "binary",
  ":metal": "fist", "metal": "fist", "fist-": "facepunch",
  "fisted": "facepunch", "facepunch": "facepunch", "e": "e2",
  "k": "ok_hand", "thumbsup": "thumbs_up", "thumbsdown": "thumbs_down",
  "+1": "thumbs_up", "-1": "thumbs_down", "^5": "thumbs_up",
  "hand": "raised_hand", "raised": "raised_hand",
  "pray": "pray", "highfive": "raised_hand", "high5": "raised_hand",
  "y": "yes", "n": "no", "yessir": "ok_hand", "nod": "ok_hand",
  "lgtm": "ok_hand", "shrug": "shrug", "tableflip": "flip",
  "table": "desktop_computer"
};